### ISSUE TITLE
교육신청 프로그램 신청자 입력 오류

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/eplabor#25]
해당 교육 프로그램에 신청이 성공하면
https://admin.eplabor.org/admin/#/eplabor/collections/eplabor_workshop_participants
DirectUs에 데이터 등록이 되도록 확인.

**Comment by mozodev** [comment]
수정 완료. 
데이터베이스에 값이 저장되고 있었는데 
status 필드 기본값이 published 이어야 하는데
public 으로 저장되서 관리 화면에 출력안되는 문제였음.
