### ISSUE TITLE
완료시 & 오픈을 위해서(~12.28)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/eplabor#3]
[검수 시 제출서류
1) 완료보고서 1부
2) 관리자 및 사용자 매뉴얼 각 1부
3) 납품 시 기타 검수에 필요한 서류 일체

[센터 확인]
1) 제가 로고 파일 등 필요한 내부 서류
2) 교육신청이랑 노동상담은 센터 내부 인원들이랑 테스트
3) 관리자 및 신청 관련해서 (모조님 전달)

**Comment by woonjjang** [comment]
@mozodev 

매뉴얼 작성하다보니
1. 메인 슬라이드 영역도 - netlify cms와 연결해야 하지 않을까 하는 (의견)
2. 교육신청 / 무료상담 부분 최종 정리해주시면 매뉴얼 완료할께요. 

50% 정도 작성 완료.

**Comment by woonjjang** [comment]
매뉴얼 쓸 일 있을 때 참고하세요. : https://drive.google.com/drive/u/1/folders/1VY3Ipnk5cdHS6B7TetCRV8ZxebAc5wf_

**Comment by mozodev** [comment]
@woonjjang 일단 실서버에 적용을 하고 담당자에게 여기까지 마무리하자고 메일은 보냈습니다.
담당자도 너무 늦어져서 행정적으로 부담스러워하고 있어서...
어떨지 모르겠는데 문서 작업을 좀 지원해주시면 좋겠... ㅎ

**Comment by woonjjang** [comment]
넘넘 고생많으셨어요. 
관련해서 행정 마무리 해 보겠습니다. ^^

**Comment by woonjjang** [comment]
관련된 산출물 및 서류 전달드립니다. 

1) 은평구노동자종합지원센터 로고.ai (전달완료)
2) 소스코드 / eplabor-master-201228.zip
3) 개발 이슈 및 이력(하단 내역 참고)-git / log-eplabor-dev.xlsx
4) 사용자 및 운영자매뉴얼.pdf(1부)
